<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, jquery carousel, jquery image slider" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body>
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/adn.jpg" alt="ADN" title="ADN" id="wows1_0"/></li>
<li><img src="data1/images/anatomie_de_la_digestion.jpg" alt="Anatomie de la digestion" title="Anatomie de la digestion" id="wows1_1"/></li>
<li><img src="data1/images/electrocardiogramme.jpg" alt="Electrocardiogramme" title="Electrocardiogramme" id="wows1_2"/></li>
<li><img src="data1/images/gntique.jpg" alt="Génétique" title="Génétique" id="wows1_3"/></li>
<li><img src="data1/images/injection.jpg" alt="Injection" title="Injection" id="wows1_4"/></li>
<li><img src="data1/images/mdecine_internationale.jpg" alt="Médecine Internationale" title="Médecine Internationale" id="wows1_5"/></li>
<li><img src="data1/images/pdiatrie.jpg" alt="Pédiatrie" title="Pédiatrie" id="wows1_6"/></li>
<li><img src="data1/images/perfusion.jpg" alt="Perfusion" title="Perfusion" id="wows1_7"/></li>
<li><img src="data1/images/radio_des_cotes.jpg" alt="Radio des cotes" title="Radio des cotes" id="wows1_8"/></li>
<li><img src="data1/images/scapula.jpg" alt="Scapula" title="Scapula" id="wows1_9"/></li>
<li><img src="data1/images/sttoscope.jpg" alt="Stétoscope" title="Stétoscope" id="wows1_10"/></li>
<li><img src="data1/images/tlmdecine.jpg" alt="Télémédecine" title="Télémédecine" id="wows1_11"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="ADN"><img src="data1/tooltips/adn.jpg" alt="ADN"/>1</a>
<a href="#" title="Anatomie de la digestion"><img src="data1/tooltips/anatomie_de_la_digestion.jpg" alt="Anatomie de la digestion"/>2</a>
<a href="#" title="Electrocardiogramme"><img src="data1/tooltips/electrocardiogramme.jpg" alt="Electrocardiogramme"/>3</a>
<a href="#" title="Génétique"><img src="data1/tooltips/gntique.jpg" alt="Génétique"/>4</a>
<a href="#" title="Injection"><img src="data1/tooltips/injection.jpg" alt="Injection"/>5</a>
<a href="#" title="Médecine Internationale"><img src="data1/tooltips/mdecine_internationale.jpg" alt="Médecine Internationale"/>6</a>
<a href="#" title="Pédiatrie"><img src="data1/tooltips/pdiatrie.jpg" alt="Pédiatrie"/>7</a>
<a href="#" title="Perfusion"><img src="data1/tooltips/perfusion.jpg" alt="Perfusion"/>8</a>
<a href="#" title="Radio des cotes"><img src="data1/tooltips/radio_des_cotes.jpg" alt="Radio des cotes"/>9</a>
<a href="#" title="Scapula"><img src="data1/tooltips/scapula.jpg" alt="Scapula"/>10</a>
<a href="#" title="Stétoscope"><img src="data1/tooltips/sttoscope.jpg" alt="Stétoscope"/>11</a>
<a href="#" title="Télémédecine"><img src="data1/tooltips/tlmdecine.jpg" alt="Télémédecine"/>12</a>
</div></div>
<span class="wsl"><a href="http://wowslider.net">jquery slideshow</a> by WOWSlider.com v5.5</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>